on: push
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@
    - name: Login to Docker Hub
      uses: docker/login-actionv2
      with:
        username: ${{ secrets.DOCKERHUB_USERNEMA }}
        password: ${{ secrets.DOCKERHUB_TOKAN }}
    - name: Build and push to Docker Hub
      uses: docker run -it -p 3001:3001
      with:
        context: .
        push: true
        tags: dianapinto01/brightstarts:${{ github.run_number }}
